eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/dbshop?useUnicode=true&characterEncoding=UTF-8&sessionVariables=FOREIGN_KEY_CHECKS=0&autoReconnect=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        globally_quoted_identifiers: true
    open-in-view: false

server:
  port: 18080

